; Using reasoning analogous to Alyssa's, describe how the difference of two intervals may be computed. 
(define (sub-interval

    ; use 4 cases like mul-interval, cuz MAYBE there are NEGATIVE numbers here...
    ; ADDITION is the special case that doesn't need min/max testing...